// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
	"time"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
)

const addCredential = `-- name: AddCredential :exec
INSERT INTO passkey_credentials(id, user_id, credential) VALUES($1, $2, $3)
`

type AddCredentialParams struct {
	ID         []byte              `json:"id"`
	UserID     uuid.UUID           `json:"user_id"`
	Credential webauthn.Credential `json:"credential"`
}

func (q *Queries) AddCredential(ctx context.Context, arg AddCredentialParams) error {
	_, err := q.db.Exec(ctx, addCredential, arg.ID, arg.UserID, arg.Credential)
	return err
}

const addSession = `-- name: AddSession :exec
INSERT INTO sessions(id, user_id, expires_at) VALUES($1, $2, $3)
`

type AddSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) error {
	_, err := q.db.Exec(ctx, addSession, arg.SessionID, arg.UserID, arg.ExpiresAt)
	return err
}

const addUser = `-- name: AddUser :exec
INSERT INTO users(id, first_name, last_name, username) VALUES($1, $2, $3, $4)
`

type AddUserParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Username  string    `json:"username"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	return err
}

const consumeSession = `-- name: ConsumeSession :one
UPDATE sessions SET is_superseded = TRUE, expires_at = NOW() + INTERVAL '5 seconds' WHERE id = $1 AND expires_at >= NOW() AND is_superseded = FALSE RETURNING id, user_id, expires_at, is_superseded
`

func (q *Queries) ConsumeSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, consumeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.IsSuperseded,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getCredentialsByUser = `-- name: GetCredentialsByUser :many
SELECT credential FROM passkey_credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialsByUser(ctx context.Context, userID uuid.UUID) ([]webauthn.Credential, error) {
	rows, err := q.db.Query(ctx, getCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []webauthn.Credential
	for rows.Next() {
		var credential webauthn.Credential
		if err := rows.Scan(&credential); err != nil {
			return nil, err
		}
		items = append(items, credential)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupersededSession = `-- name: GetSupersededSession :one
SELECT id, user_id, expires_at, is_superseded FROM sessions WHERE id = $1 AND expires_at >= NOW() AND is_superseded = TRUE
`

func (q *Queries) GetSupersededSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSupersededSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.IsSuperseded,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, username FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
	)
	return i, err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE passkey_credentials SET credential = $1 WHERE id = $2
`

type UpdateCredentialParams struct {
	Credential webauthn.Credential `json:"credential"`
	ID         []byte              `json:"id"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential, arg.Credential, arg.ID)
	return err
}

const verifyCredentialOwner = `-- name: VerifyCredentialOwner :one
SELECT EXISTS(SELECT 1 FROM passkey_credentials WHERE id = $1 AND user_id = $2)
`

type VerifyCredentialOwnerParams struct {
	CredID []byte    `json:"cred_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) VerifyCredentialOwner(ctx context.Context, arg VerifyCredentialOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyCredentialOwner, arg.CredID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
