// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
)

const addCredential = `-- name: AddCredential :exec
INSERT INTO passkey_credentials(id, user_id, credential) VALUES($1, $2, $3)
`

type AddCredentialParams struct {
	ID         []byte              `json:"id"`
	UserID     uuid.UUID           `json:"user_id"`
	Credential webauthn.Credential `json:"credential"`
}

func (q *Queries) AddCredential(ctx context.Context, arg AddCredentialParams) error {
	_, err := q.db.Exec(ctx, addCredential, arg.ID, arg.UserID, arg.Credential)
	return err
}

const addUser = `-- name: AddUser :exec
INSERT INTO users(id, first_name, last_name, username) VALUES($1, $2, $3, $4)
`

type AddUserParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Username  string    `json:"username"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	return err
}
